version: '3.8'

services:
  laravel:
    build:
      dockerfile: ./Dockerfile
    platform: linux/amd64
    volumes:
      - laravel-volume:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      db-utbm:
        condition: service_healthy

  db-utbm:
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_UTBM}
      - MYSQL_USER=${DB_USERNAME_UTBM}
      - MYSQL_PASSWORD=${DB_PASSWORD_UTBM}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD_UTBM}
    volumes:
      - db-utbm-data:/var/lib/mysql
      - ./UTBM.sql:/docker-entrypoint-initdb.d/UTBM.sql
    ports:
      - "${DB_PORT_UTBM}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-c", "1"]
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:latest
    platform: linux/amd64
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - laravel-volume:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - laravel
    command: /bin/bash -c "nginx -g 'daemon off;'"

volumes:
  laravel-volume:
  db-utbm-data: